[package]
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"
name = "sql-migration-connector"
version = "0.1.0"

[dependencies]
datamodel = {path = "../../../libs/datamodel/core"}
datamodel-connector = {path = "../../../libs/datamodel/connectors/datamodel-connector"}
migration-connector = {path = "../migration-connector"}
native-types = {path = "../../../libs/native-types"}
prisma-value = {path = "../../../libs/prisma-value"}
sql-schema-describer = {path = "../../../libs/sql-schema-describer"}
user-facing-errors = {path = "../../../libs/user-facing-errors", features = ["sql"]}

anyhow = "1.0.26"
async-trait = "0.1.17"
barrel = {git = "https://github.com/prisma/barrel.git", features = ["sqlite3", "mysql", "pg", "mssql"], branch = "mssql-support"}
chrono = { version = "0.4" }
connection-string = "0.1.10"
enumflags2 = "0.6.0"
once_cell = "1.3"
regex = "1"
serde = {version = "1.0", features = ["derive"]}
serde_json = { version = "1.0", features = ["float_roundtrip"] }
tokio = {version = "0.2.13", default-features = false, features = ["time"]}
tracing = "0.1.10"
tracing-futures = "0.2.0"
url = "2.1.1"
uuid = { version = "0.8", features = ["v4"] }
indoc = "1.0"

[dependencies.quaint]
git = "https://github.com/prisma/quaint"
features = [
    "json",
    "uuid",
    "chrono",
    "sqlite",
    "bigdecimal",
    "postgresql",
    "mysql",
    "mssql",
    "tracing-log"
]
